---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npminstall
spec:
  workspaces:
    - name: source
  steps:
    - name: install
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        echo "***** Environment *****"
        npm --version
        pwd

        echo "***** Cleaning npm cache *****"
        npm cache clean --force

        echo "***** Running npm install *****"
        npm install

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        set -e
        echo "***** Running jasminetests *****"
        npx jasmine
